"""change phone Column from BigInteger to String(11)

Revision ID: 3209a1d5cc58
Revises: d8dce0da9035
Create Date: 2025-09-28 14:42:08.504728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3209a1d5cc58'
down_revision: Union[str, Sequence[str], None] = 'd8dce0da9035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('online_shop_users', 'phone',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=11),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('online_shop_users', 'phone',
               existing_type=sa.String(length=11),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
