"""Добавлен Enum MODERATOR

Revision ID: 83e5574ce49e
Revises: 837ab3a29011
Create Date: 2025-10-12 14:32:50.208380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e5574ce49e'
down_revision: Union[str, Sequence[str], None] = '837ab3a29011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_role_enum ADD VALUE 'MODERATOR' AFTER 'USER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
