"""add name, phone, address to users

Revision ID: d8dce0da9035
Revises: c974b9f93f6f
Create Date: 2025-09-28 14:22:33.316663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8dce0da9035'
down_revision: Union[str, Sequence[str], None] = 'c974b9f93f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('online_shop_users', sa.Column('name', sa.String(length=30), nullable=True))
    op.add_column('online_shop_users', sa.Column('phone', sa.BigInteger(), nullable=True))
    op.add_column('online_shop_users', sa.Column('address', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('online_shop_users', 'address')
    op.drop_column('online_shop_users', 'phone')
    op.drop_column('online_shop_users', 'name')
    # ### end Alembic commands ###
