EN = {
    "/start_registered": """please press button <b>☑️ categories</b>,
to see our offers""",
    "need_registration": """You are don't registered in our system
To get started, please enter the command /start""",
    "wellcome": "Wellcome to the test shop, {}!\nPlease, select the desired menu item.",
    "cancel_command": """Nothing to cancel.
To place an order, click '✍🏻 place an order.'""",
    "cancel_command_success": """You have exited the data filling state.
To place an order, click '✍🏻 place an order.'""",
    "button_cart": "🛒 cart",
    "button_category": "☑️ categories",
    'category': "Select a product category",
    "button_order": "✍🏻 place an order",
    "button_contacts": "📞 our contacts",
    'contacts': "We develop software for your business.\n\n"
                "To order a full-fledged online store directly in Telegram, contact us:\n"
                "📞 +998-93-529-74-55 - Dmitriy\n✍🏻 Telegram: @jsdeemon @SafaDmitry",
    "/start_description": "Restart bot",
    "/lang_description": "Change language",
    "/ban_description": "Ban a user (requires user_id or username)",
    "/unban_description": "Unban the user (requires user_id or username)",
    "Unknown command": "I don't know this command.\nplease use the menu",
    "prev": "previous",
    "next": "next",
    "add_to_cart": "add to cart",
    "cart_empty": "Your cart is empty",
    "calculate_cart": "Total: <b>{:,} сум</b>",
    "order_cart_empty": "Your cart is empty. Please, choose goods",
    "edit_cart_button": "❌ DELETE",
    "item_added": "The product has been added to the cart",
    "write_name": "To place an order, please write your bane:",
    "write_correct_name": "Please enter a valid name (letters only, 2 or more characters",
    "write_phone": "Please enter your phone number (only numbers starting with 8):",
    "write_correct_phone": "Please enter correct phone number (only numbers starting with 8):",
    "write_address": "Please enter the delivery address in any format",
    "cancel_write": "If you want to stop filling the data, enter the command /cancel",
    "confirm": "Confirm",
    "correct": "To correct",
    "confirm_text": "Please, check your details:\nName: {}\nNumber: {}\nAddress: {}",
    "your_order_total": "Your order for the total amount: {:,.2f} сум:",
    "thanks_for_order": "Thank you for your order. We will contact you shortly",
    "save_lang_button_text": "✅ Save",
    "cancel_lang_button_text": "Cancel",
    "choose_lang": "Choose language",
    "ru": "🇷🇺 Russian",
    "en": "🇬🇧 English",
    "lang_saved": "The language has been successfully changed",
    "lang_cancelled": "OK, your language is still: {}.\n\nYou can send me something or "
                      "send a command /help",
    "empty_ban_answer": "❗ Please specify the user's ID or @username.",
    "empty_unban_answer": "❗ Please specify the user's ID or @username.",
    "incorrect_ban_arg": "⚠️ <b>Incorrect format.</b>\n\nUse /ban <code>ID</code> "
                         "or /ban <code>@username</code>",
    "incorrect_unban_arg": "⚠️ <b>Incorrect format.</b>\n\nUse /unban <code>ID</code> "
                           "or /unban <code>@username</code>",
    "no_user": "❗ There is no such user in the database!",
    "already_banned": "❗ The user is already banned!",
    "successfully_banned": "⚠️ The user has been successfully banned!",
    "successfully_unbanned": "⚠️ The user has been successfully unbanned!",
    "not_banned": "❗ The user was not banned anyway!",
    "categories_not_found": "There are no categories",
    "items_not_found": "There are no products in this category yet",
    "need_admin_rights": "To ger file_id you need administrator rights",
    "dont_flood": "⏳ Too many requests. Try again later.",
}